version: '3'
services:
  gateway:
    image: prime-rhel:latest
    container_name: gateway
    command: /usr/sbin/sshd -D
    ports:
      - "2200:22"
    networks:
      - oracle-network
    expose:
      - "22"  # Expose the port to other containers on the same network

  oraclelinux1:
    image: prime-rhel:latest
    container_name: oraclelinux1
    command: /usr/sbin/sshd -D
    networks:
      - oracle-network

  oraclelinux2:
    image: prime-rhel:latest
    container_name: oraclelinux2
    command: /usr/sbin/sshd -D
    networks:
      - oracle-network

networks:
  oracle-network:
    driver: bridge
