- name: Setup all nodes
  hosts: from-outside-gateway oracledb
  gather_facts: false
  tasks:
    - name: Copy bashrc
      ansible.builtin.copy:
        src: /root/.bashrc
        dest: /home/prime/.bashrc
        remote_src: true # By default copies from controller to the node.
      become: true

- name: Manage gateway node.
  hosts: from-outside-gateway
  gather_facts: false
  roles: 
    - bastion
  tasks:
    - name: Test
      delegate_to: from-outside-gateway
      ansible.builtin.command: hostname
      register: gateway_result

- name: Manage Oracle DB group
  hosts: oracledb
  gather_facts: true
  roles: 
    - bastion-minion
  tasks:
    # - name: Print out all the facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Your task 1
      ansible.builtin.debug:
        msg: 
          - hostname: "{{ ansible_facts['nodename'] }} "
          # - python_exe: "{{ ansible_facts['discovered_interpreter_python'] }}"
          - python_version: "{{ ansible_facts['python_version'] }}"

    - name: Your task 2
      ansible.builtin.command: ls

    # - name: Check sshd
    #   service:
    #     name: sshd
    #     state: started
